namespace BlazorBootstrap;

public static class FeatherIconUtility
{
    /// <summary>
    /// The prefix for all Feather icons.
    /// </summary>
    public static string Icon()
    {
        return "ft";
    }

    /// <summary>
    /// Returns the CSS class for the specified icon name.
    /// </summary>
    /// <param name="iconName">The icon name.</param>
    /// <returns>The CSS class for the icon.</returns>
    public static string Icon(FeatherIconName iconName)
    {
        return $"{Icon()}-{ToIconName(iconName)}";
    }

    /// <summary>
    /// Returns the CSS class for the specified icon size.
    /// </summary>
    /// <param name="iconSize">The icon size.</param>
    /// <returns>The CSS class for the icon size, or null if the size is not supported.</returns>
    public static string? IconSize(IconSize iconSize)
    {
        return iconSize switch
        {
            BlazorBootstrap.IconSize.x1 => "fs-1",
            BlazorBootstrap.IconSize.x2 => "fs-2",
            BlazorBootstrap.IconSize.x3 => "fs-3",
            BlazorBootstrap.IconSize.x4 => "fs-4",
            BlazorBootstrap.IconSize.x5 => "fs-5",
            BlazorBootstrap.IconSize.x6 => "fs-6",
            _ => null
        };
    }

    /// <summary>
    /// Converts an icon name to its corresponding CSS class name.
    /// </summary>
    /// <param name="iconName">The icon name.</param>
    /// <returns>The CSS class name for the icon.</returns>
    public static string ToIconName(FeatherIconName iconName)
    {
        return iconName switch
        {
            FeatherIconName.Activity => "activity",
            FeatherIconName.Airplay => "airplay",
            FeatherIconName.AlertCircle => "alert-circle",
            FeatherIconName.AlertOctagon => "alert-octagon",
            FeatherIconName.AlertTriangle => "alert-triangle",
            FeatherIconName.AlignCenter => "align-center",
            FeatherIconName.AlignJustify => "align-justify",
            FeatherIconName.AlignLeft => "align-left",
            FeatherIconName.AlignRight => "align-right",
            FeatherIconName.Anchor => "anchor",
            FeatherIconName.Aperture => "aperture",
            FeatherIconName.Archive => "archive",
            FeatherIconName.ArrowDown => "arrow-down",
            FeatherIconName.ArrowDownCircle => "arrow-down-circle",
            FeatherIconName.ArrowDownLeft => "arrow-down-left",
            FeatherIconName.ArrowDownRight => "arrow-down-right",
            FeatherIconName.ArrowLeft => "arrow-left",
            FeatherIconName.ArrowLeftCircle => "arrow-left-circle",
            FeatherIconName.ArrowRight => "arrow-right",
            FeatherIconName.ArrowRightCircle => "arrow-right-circle",
            FeatherIconName.ArrowUp => "arrow-up",
            FeatherIconName.ArrowUpCircle => "arrow-up-circle",
            FeatherIconName.ArrowUpLeft => "arrow-up-left",
            FeatherIconName.ArrowUpRight => "arrow-up-right",
            FeatherIconName.AtSign => "at-sign",
            FeatherIconName.Award => "award",
            FeatherIconName.BarChart => "bar-chart",
            FeatherIconName.BarChart2 => "bar-chart-2",
            FeatherIconName.Battery => "battery",
            FeatherIconName.BatteryCharging => "battery-charging",
            FeatherIconName.Bell => "bell",
            FeatherIconName.BellOff => "bell-off",
            FeatherIconName.Bluetooth => "bluetooth",
            FeatherIconName.Bold => "bold",
            FeatherIconName.Book => "book",
            FeatherIconName.Bookmark => "bookmark",
            FeatherIconName.BookOpen => "book-open",
            FeatherIconName.Box => "box",
            FeatherIconName.Briefcase => "briefcase",
            FeatherIconName.Calendar => "calendar",
            FeatherIconName.Camera => "camera",
            FeatherIconName.CameraOff => "camera-off",
            FeatherIconName.Cast => "cast",
            FeatherIconName.Check => "check",
            FeatherIconName.CheckCircle => "check-circle",
            FeatherIconName.CheckSquare => "check-square",
            FeatherIconName.ChevronDown => "chevron-down",
            FeatherIconName.ChevronLeft => "chevron-left",
            FeatherIconName.ChevronRight => "chevron-right",
            FeatherIconName.ChevronsDown => "chevrons-down",
            FeatherIconName.ChevronsLeft => "chevrons-left",
            FeatherIconName.ChevronsRight => "chevrons-right",
            FeatherIconName.ChevronsUp => "chevrons-up",
            FeatherIconName.ChevronUp => "chevron-up",
            FeatherIconName.Chrome => "chrome",
            FeatherIconName.Circle => "circle",
            FeatherIconName.Clipboard => "clipboard",
            FeatherIconName.Clock => "clock",
            FeatherIconName.Cloud => "cloud",
            FeatherIconName.CloudDrizzle => "cloud-drizzle",
            FeatherIconName.CloudLightning => "cloud-lightning",
            FeatherIconName.CloudOff => "cloud-off",
            FeatherIconName.CloudRain => "cloud-rain",
            FeatherIconName.CloudSnow => "cloud-snow",
            FeatherIconName.Code => "code",
            FeatherIconName.Codepen => "codepen",
            FeatherIconName.Codesandbox => "codesandbox",
            FeatherIconName.Coffee => "coffee",
            FeatherIconName.Columns => "columns",
            FeatherIconName.Command => "command",
            FeatherIconName.Compass => "compass",
            FeatherIconName.Copy => "copy",
            FeatherIconName.CornerDownLeft => "corner-down-left",
            FeatherIconName.CornerDownRight => "corner-down-right",
            FeatherIconName.CornerLeftDown => "corner-left-down",
            FeatherIconName.CornerLeftUp => "corner-left-up",
            FeatherIconName.CornerRightDown => "corner-right-down",
            FeatherIconName.CornerRightUp => "corner-right-up",
            FeatherIconName.CornerUpLeft => "corner-up-left",
            FeatherIconName.CornerUpRight => "corner-up-right",
            FeatherIconName.Cpu => "cpu",
            FeatherIconName.CreditCard => "credit-card",
            FeatherIconName.Crop => "crop",
            FeatherIconName.Crosshair => "crosshair",
            FeatherIconName.Database => "database",
            FeatherIconName.Delete => "delete",
            FeatherIconName.Disc => "disc",
            FeatherIconName.Divide => "divide",
            FeatherIconName.DivideCircle => "divide-circle",
            FeatherIconName.DivideSquare => "divide-square",
            FeatherIconName.DollarSign => "dollar-sign",
            FeatherIconName.Download => "download",
            FeatherIconName.DownloadCloud => "download-cloud",
            FeatherIconName.Dribble => "dribble",
            FeatherIconName.Droplet => "droplet",
            FeatherIconName.Edit => "edit",
            FeatherIconName.Edit2 => "edit-2",
            FeatherIconName.Edit3 => "edit-3",
            FeatherIconName.ExternalLink => "external-link",
            FeatherIconName.Eye => "eye",
            FeatherIconName.EyeOff => "eye-off",
            FeatherIconName.Facebook => "facebook",
            FeatherIconName.FastForward => "fast-forward",
            FeatherIconName.Feather => "feather",
            FeatherIconName.Figma => "figma",
            FeatherIconName.File => "file",
            FeatherIconName.FileMinus => "file-minus",
            FeatherIconName.FilePlus => "file-plus",
            FeatherIconName.FileText => "file-text",
            FeatherIconName.Film => "film",
            FeatherIconName.Filter => "filter",
            FeatherIconName.Flag => "flag",
            FeatherIconName.Folder => "folder",
            FeatherIconName.FolderMinus => "folder-minus",
            FeatherIconName.FolderPlus => "folder-plus",
            FeatherIconName.Framer => "framer",
            FeatherIconName.Frown => "frown",
            FeatherIconName.Gift => "gift",
            FeatherIconName.GitBranch => "git-branch",
            FeatherIconName.GitCommit => "git-commit",
            FeatherIconName.Github => "github",
            FeatherIconName.Gitlab => "gitlab",
            FeatherIconName.GitMerge => "git-merge",
            FeatherIconName.GitPullRequest => "git-pull-request",
            FeatherIconName.Globe => "globe",
            FeatherIconName.Grid => "grid",
            FeatherIconName.HardDrive => "hard-drive",
            FeatherIconName.Hash => "hash",
            FeatherIconName.Headphones => "headphones",
            FeatherIconName.Heart => "heart",
            FeatherIconName.HelpCircle => "help-circle",
            FeatherIconName.Hexagon => "hexagon",
            FeatherIconName.Home => "home",
            FeatherIconName.Image => "image",
            FeatherIconName.Inbox => "inbox",
            FeatherIconName.Info => "info",
            FeatherIconName.Instagram => "instagram",
            FeatherIconName.Italic => "italic",
            FeatherIconName.Key => "key",
            FeatherIconName.Layers => "layers",
            FeatherIconName.Layout => "layout",
            FeatherIconName.LifeBuoy => "life-buoy",
            FeatherIconName.Link => "link",
            FeatherIconName.Link2 => "link-2",
            FeatherIconName.Linkedin => "linkedin",
            FeatherIconName.List => "list",
            FeatherIconName.Loader => "loader",
            FeatherIconName.Lock => "lock",
            FeatherIconName.LogIn => "log-in",
            FeatherIconName.LogOut => "log-out",
            FeatherIconName.Mail => "mail",
            FeatherIconName.Map => "map",
            FeatherIconName.MapPin => "map-pin",
            FeatherIconName.Maximize => "maximize",
            FeatherIconName.Maximize2 => "maximize-2",
            FeatherIconName.Meh => "meh",
            FeatherIconName.Menu => "menu",
            FeatherIconName.MessageCircle => "message-circle",
            FeatherIconName.MessageSquare => "message-square",
            FeatherIconName.Mic => "mic",
            FeatherIconName.MicOff => "mic-off",
            FeatherIconName.Minimize => "minimize",
            FeatherIconName.Minimize2 => "minimize-2",
            FeatherIconName.Minus => "minus",
            FeatherIconName.MinusCircle => "minus-circle",
            FeatherIconName.MinusSquare => "minus-square",
            FeatherIconName.Monitor => "monitor",
            FeatherIconName.Moon => "moon",
            FeatherIconName.MoreHorizontal => "more-horizontal",
            FeatherIconName.MoreVertical => "more-vertical",
            FeatherIconName.MousePointer => "mouse-pointer",
            FeatherIconName.Move => "move",
            FeatherIconName.Music => "music",
            FeatherIconName.Navigation => "navigation",
            FeatherIconName.Navigation2 => "navigation-2",
            FeatherIconName.Octagon => "octagon",
            FeatherIconName.Package => "package",
            FeatherIconName.Paperclip => "paperclip",
            FeatherIconName.Pause => "pause",
            FeatherIconName.PauseCircle => "pause-circle",
            FeatherIconName.PenTool => "pen-tool",
            FeatherIconName.Percent => "percent",
            FeatherIconName.Phone => "phone",
            FeatherIconName.PhoneCall => "phone-call",
            FeatherIconName.PhoneForwarded => "phone-forwarded",
            FeatherIconName.PhoneIncoming => "phone-incoming",
            FeatherIconName.PhoneMissed => "phone-missed",
            FeatherIconName.PhoneOff => "phone-off",
            FeatherIconName.PhoneOutgoing => "phone-outgoing",
            FeatherIconName.PieChart => "pie-chart",
            FeatherIconName.Play => "play",
            FeatherIconName.PlayCircle => "play-circle",
            FeatherIconName.Plus => "plus",
            FeatherIconName.PlusCircle => "plus-circle",
            FeatherIconName.PlusSquare => "plus-square",
            FeatherIconName.Pocket => "pocket",
            FeatherIconName.Power => "power",
            FeatherIconName.Printer => "printer",
            FeatherIconName.Radio => "radio",
            FeatherIconName.RefreshCcw => "refresh-ccw",
            FeatherIconName.RefreshCw => "refresh-cw",
            FeatherIconName.Repeat => "repeat",
            FeatherIconName.Rewind => "rewind",
            FeatherIconName.RotateCcw => "rotate-ccw",
            FeatherIconName.RotateCw => "rotate-cw",
            FeatherIconName.Rss => "rss",
            FeatherIconName.Save => "save",
            FeatherIconName.Scissors => "scissors",
            FeatherIconName.Search => "search",
            FeatherIconName.Send => "send",
            FeatherIconName.Server => "server",
            FeatherIconName.Settings => "settings",
            FeatherIconName.Share => "share",
            FeatherIconName.Share2 => "share-2",
            FeatherIconName.Shield => "shield",
            FeatherIconName.ShieldOff => "shield-off",
            FeatherIconName.ShoppingBag => "shopping-bag",
            FeatherIconName.ShoppingCart => "shopping-cart",
            FeatherIconName.Shuffle => "shuffle",
            FeatherIconName.Sidebar => "sidebar",
            FeatherIconName.SkipBack => "skip-back",
            FeatherIconName.SkipForward => "skip-forward",
            FeatherIconName.Slack => "slack",
            FeatherIconName.Slash => "slash",
            FeatherIconName.Sliders => "sliders",
            FeatherIconName.Smartphone => "smartphone",
            FeatherIconName.Smile => "smile",
            FeatherIconName.Speaker => "speaker",
            FeatherIconName.Square => "square",
            FeatherIconName.Star => "star",
            FeatherIconName.StopCircle => "stop-circle",
            FeatherIconName.Sun => "sun",
            FeatherIconName.Sunrise => "sunrise",
            FeatherIconName.Sunset => "sunset",
            FeatherIconName.Table => "table",
            FeatherIconName.Tablet => "tablet",
            FeatherIconName.Tag => "tag",
            FeatherIconName.Target => "target",
            FeatherIconName.Terminal => "terminal",
            FeatherIconName.Thermometer => "thermometer",
            FeatherIconName.ThumbsDown => "thumbs-down",
            FeatherIconName.ThumbsUp => "thumbs-up",
            FeatherIconName.ToggleLeft => "toggle-left",
            FeatherIconName.ToggleRight => "toggle-right",
            FeatherIconName.Tool => "tool",
            FeatherIconName.Trash => "trash",
            FeatherIconName.Trash2 => "trash-2",
            FeatherIconName.Trello => "trello",
            FeatherIconName.TrendingDown => "trending-down",
            FeatherIconName.TrendingUp => "trending-up",
            FeatherIconName.Triangle => "triangle",
            FeatherIconName.Truck => "truck",
            FeatherIconName.Tv => "tv",
            FeatherIconName.Twitch => "twitch",
            FeatherIconName.Twitter => "twitter",
            FeatherIconName.Type => "type",
            FeatherIconName.Umbrella => "umbrella",
            FeatherIconName.Underline => "underline",
            FeatherIconName.Unlock => "unlock",
            FeatherIconName.Upload => "upload",
            FeatherIconName.UploadCloud => "upload-cloud",
            FeatherIconName.User => "user",
            FeatherIconName.UserCheck => "user-check",
            FeatherIconName.UserMinus => "user-minus",
            FeatherIconName.UserPlus => "user-plus",
            FeatherIconName.Users => "users",
            FeatherIconName.UserX => "user-x",
            FeatherIconName.Video => "video",
            FeatherIconName.VideoOff => "video-off",
            FeatherIconName.Voicemail => "voicemail",
            FeatherIconName.Volume => "volume",
            FeatherIconName.Volume1 => "volume-1",
            FeatherIconName.Volume2 => "volume-2",
            FeatherIconName.VolumeX => "volume-x",
            FeatherIconName.Watch => "watch",
            FeatherIconName.Wifi => "wifi",
            FeatherIconName.WifiOff => "wifi-off",
            FeatherIconName.Wind => "wind",
            FeatherIconName.X => "x",
            FeatherIconName.XCircle => "x-circle",
            FeatherIconName.XOctagon => "x-octagon",
            FeatherIconName.XSquare => "x-square",
            FeatherIconName.Youtube => "youtube",
            FeatherIconName.Zap => "zap",
            FeatherIconName.ZapOff => "zap-off",
            FeatherIconName.ZoomIn => "zoom-in",
            FeatherIconName.ZoomOut => "zoom-out",

            _ => ""
        };
    }
}
